service: kache-lambda
useDotenv: true

frameworkVersion: '2'

provider:
  name: aws
  stage: dev
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-2
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    ETH_NODE_URL: ${env:ETH_NODE_URL}
    ETHERSCAN_API_KEY: ${env:ETHERSCAN_API_KEY}
    COINLAYER_ACCESS_KEY: ${env:COINLAYER_ACCESS_KEY}
    MYOB_PUBLIC_KEY: ${env:MYOB_PUBLIC_KEY}
    MYOB_PRIVATE_KEY: ${env:MYOB_PRIVATE_KEY}

functions:
  query-blockchain-payments:
    name: QueryBlockchainPayments
    description: Queries payments on the blockchain and links them to MYOB asset accounts
    handler: dist/lambda.handler
    events:
      - http: GET /api/automation/query-blockchain-payments

  exchange:
    name: CurrencyExchange
    description: Converts an NZD value to an ethereum value (or just exchange rate)
    handler: dist/lambda.handler
    events:
      - http: GET /api/client/exchange

  onboard-unlinked:
    name: OnboardUnlinked
    description: Creates a new user on our DB that is not linked with MYOB
    handler: dist/lambda.handler
    events:
      - http: POST /api/client/onboard-unlinked

  myob-auth-callback:
    name: MyobAuthentication
    description: Link existing UserId with MYOB account
    handler: dist/lambda.handler
    events:
      - http: POST /api/client/myob-auth

plugins:
  - serverless-offline
